spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/webflux
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: TRACE

redis:
  expiration: 5
jwt:
  secret: e7918a5ed84f1c35da180cadc375efa01bd50323f27b747bd6b802cefa48f487
  expiration: 86400000

endpoint:
  rikyandmorty: https://rickandmortyapi.com/api

#spring:
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/shopping_reactive
#    username: postgres
#    password: 12345
#
#  flyway:
#      url: jdbc:postgresql://localhost:5432/shopping_reactive
#      user: postgres
#      password: 12345

